version: '3'
services:
  web:
    image: image_processor:latest
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  rq_worker:
    image: image_processor:latest
    command: rq worker -u redis://redis:6379
    depends_on:
      - redis