version: '3'
services:
  api:
    image: image_processor:latest
    command: python api.py
    ports:
      - "5000:5000"
    volumes:
      - static-content:/static
  redis:
    image: "redis:alpine"
  rq_worker:
    image: image_processor:latest
    command: rq worker -u redis://redis:6379
    depends_on:
      - redis
    volumes:
      - static-content:/static

volumes:
  static-content: